name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 18

      - name: Build App
        working-directory:  frontend
        run: |
          npm install
          npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          branch: smallweb
          create_branch: true
          file_pattern: 'main.ts deno.json deno.lock dist'
          add_options: '--force'

